### ISSUE TITLE
Getting a BinaryWriteFailedException when using PgBulkInsert

### ISSUE THREAD

**Issue by msylla** [PgBulkInsert/PgBulkInsert#114]
Hi,

I've been scrupulously following your tutorial but getting a :

```
de.bytefish.pgbulkinsert.exceptions.BinaryWriteFailedException: org.postgresql.util.PSQLException: ERREUR: format de données binaires incorrect
  Où : COPY aft, ligne 1, colonne id_aft
	at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:215)
	at de.bytefish.pgbulkinsert.PgBulkInsert.saveAll(PgBulkInsert.java:42)
	at de.bytefish.pgbulkinsert.PgBulkInsert.saveAll(PgBulkInsert.java:46)
---------
Caused by: org.postgresql.util.PSQLException: ERREUR: format de données binaires incorrect
  Où : COPY aft, ligne 1, colonne id_aft
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1116)
	at org.postgresql.core.v3.QueryExecutorImpl.flushCopy(QueryExecutorImpl.java:1013)
	at org.postgresql.core.v3.CopyInImpl.flushCopy(CopyInImpl.java:41)
	at org.postgresql.copy.PGCopyOutputStream.flush(PGCopyOutputStream.java:118)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:141)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:210)
```
Can i get some guidance/understanding to resolve that issue ? 

Using Postgres 12 and JDK8

**Comment by bytefish** [comment]
@msylla Could you provide an example to reproduce the error?

**Comment by bytefish** [comment]
@msylla Sometimes the problem is, that the data types don‘t match between the database and the Java type. For example using a BigDecimal or BigInteger, where an int should be used. This leads to weird errors like this, because the API doesn‘t validate between the actual table in the database and your mapping, but just spits out the Binary data. And if your mappings don‘t match, then Postgres expects data from the stream, when it has already ended and errs out.

**Comment by msylla** [comment]
Sorry for the late reply, i will try to check the ORM in depth. Thanks for the return.
