### ISSUE TITLE
Jpa Mapping quoting exception

### ISSUE THREAD

**Issue by jeffzoch** [PgBulkInsert/PgBulkInsert#91]
I cant seem to get jpa mapping working. 

I have an entity like this: 
```kotlin
@Entity
data class Ticket(
    @Id
    val ticketId: String = UUID.randomUUID().toString(),
    val jobId: String = UUID.randomUUID().toString(),
    val entityId: String? = "",
    val stepNo: Long = 0,
    val opType: String,
    @Enumerated(EnumType.STRING)
    val status: TicketStatus = TicketStatus.NEW,
    val createdBy: String? = "",
    val resetBy: String? = "",
    val scheduledStartTime: Timestamp = Timestamp.from(Instant.now()),
    val scheduledEndTime: Timestamp? = null,
    val startTime: Timestamp? = null,
    val endTime: Timestamp? = null,
    val retryable: Boolean = true,
    val retryCount: Int = 0,
    val cleanupStep: Int = 0,
    val assignedTo: String? = "",
    val externalRefId: String? = "",
    @field:Column(length = 1000)
    val ticketDetail: String? = "",
    @CreationTimestamp
    val createdTime: Timestamp = Timestamp.from(Instant.now()),
    val updatedBy: String? = "",
    val dryRun: Boolean = false,
    val cancelRequested: Boolean = false,
    val abortCode: String? = null,
    val errorCode: String? = null
)
```

and when I do 
```kotlin
return PostgreSqlUtils.tryGetPGConnection(jdbcTemplate.dataSource?.connection).map {
            logger.info("Using postgres copy for insertion")
            val mapping = JpaMapping(Ticket::class.java)
            val bulkInsert = PgBulkInsert(mapping)
            bulkInsert.saveAll(it, tickets)
            true
        }.orElse(false)
```
I get the following exception:
```
String index out of range: 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at de.bytefish.pgbulkinsert.util.PostgreSqlUtils.requiresQuoting(PostgreSqlUtils.java:69)
	at de.bytefish.pgbulkinsert.util.PostgreSqlUtils.quoteIdentifier(PostgreSqlUtils.java:50)
	at de.bytefish.pgbulkinsert.mapping.AbstractMapping.lambda$getCopyCommand$9(AbstractMapping.java:363)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.bytefish.pgbulkinsert.mapping.AbstractMapping.getCopyCommand(AbstractMapping.java:364)
	at de.bytefish.pgbulkinsert.PgBulkInsert.saveAll(PgBulkInsert.java:39)
	at de.bytefish.pgbulkinsert.PgBulkInsert.saveAll(PgBulkInsert.java:46)
```

**Comment by bytefish** [comment]
The JpaMapping only works with a class annotated with ``@Table`` and properties annotated with a ``@Column``. 

I didn't implement a version for mapping by Property name (which would be a nice feature?). 

Could you please try if adding an @Table and @Column annotations help?

**Comment by jeffzoch** [comment]
That seemed to help though now im getting 
```
Java Type class java.sql.Timestamp is not supported yet.
``` 
darn :/ . 

Btw, it would be really convenient if you could look at hibernate metadata to access the table name, column names, and column types. Might be a bit easier since its already parsing that stuff for jpa

**Comment by bytefish** [comment]
Well yes, that's why I thought for a long time to support JPA at all. There are so many things like you mention and I will probably never implement One To One or One To Many Relationships. Let me have a quick look, how you can write Timestamps.

**Comment by jeffzoch** [comment]
Totally get it. I dont use 1:1 or many to many as its too complex and not-sql-like. I just use jpa for table mapping really. 

I saw you have an example that implements AbstractMapping for timestamp. THe only issue I see is that I want to use the JpaMapping but pass in an additional override. It looks like I can either choose JpaMapping or some new extension of AbtractMapping with no way to merge the two (either by passing new behavior to JpaMapping or extracting JpaMapping's info and passing it to my new type)

**Comment by bytefish** [comment]
Exactely! The ``JpaMapping<>`` API is way too closed. I will see how to make it easier to extend. The whole ``AbstractMapping`` yields a nice API regarding the ``mapXyz(...)`` methods, but type erasure makes it impossible to say:

* ``mapTimestamp(string columnName, Function<T, Timestamp>)``
* ``mapTimestamp(string columnName, Function<T, LocalDateTime>)``

Just because both functions will be a ``Function<T, Object>`` at Runtime... 

What I think of would be something like providing an optional ``Function<???, LocalDateTime>`` converter, that could be executed before running ``mapTimestamp`` and the 

But honestly: You just want to write ``mapTimestamp(string columnName, myTimestampValue)``. I will fix this now and see, how to do it.

**Comment by jeffzoch** [comment]
Right now i have something like:
```kotlin
logger.info("Using postgres copy for insertion")
                    val typeMap = PostgresTypeMapping().mappings.apply {
                        put(Timestamp::class.java, DataType.Timestamp)
                    }
                    class TicketMapping(entityClass: Class<Ticket> = Ticket::class.java,
                                        typeMapping: IPostgresTypeMapping = PostgresTypeMapping(),
                                        columnMapping: MutableMap<String, DataType> = mutableMapOf() ,
                                        usePostgresQuoting: Boolean = false
                    ) : JpaMapping<Ticket>(entityClass, typeMapping, columnMapping, usePostgresQuoting) {
                        init {
                            this.getColumns().removeIf { c ->
                                    c.columnName == "scheduled_start_time"
                                    || c.columnName== "scheduled_end_time"
                                            || c.columnName== "start_time"
                                            || c.columnName== "end_time"
                                            || c.columnName == "created_time"
                            }

                            mapTimeStamp("scheduled_start_time") {t: Ticket -> t.scheduledStartTime.toLocalDateTime() }
                            mapTimeStamp("scheduled_end_time") {t: Ticket -> t.scheduledEndTime?.toLocalDateTime()  }
                            mapTimeStamp("start_time") {t: Ticket -> t.startTime?.toLocalDateTime() }
                            mapTimeStamp("end_time") {t: Ticket -> t.endTime?.toLocalDateTime() }
                            mapTimeStamp("created_time") {t: Ticket -> t.createdTime.toLocalDateTime() }

                        }
                    }
                    val mapping = TicketMapping(typeMapping = PostgresTypeMapping(typeMap))
                    val bulkInsert = PgBulkInsert(mapping)
                    logger.info("Copy: ${mapping.copyCommand}")
                    bulkInsert.saveAll(it, tickets)
```
But im getting some errors about not enough data left. The main weird spots above are:
1. having to specify the columns explicitly for each conversion - its explicit but maybe too much? ``` 
mapTimestamp(Class<T> klass, Function<T, LocalDateTime> ) 
```
could be nice.
2. Having to remove column definitions from jpaMapping since the default constructor already put them there.

**Comment by bytefish** [comment]
Yes, no. This looks way to complicated for what should be a simple Java <-> SQL Table mapping. If you reach this point, you might just use the ``AbstractMapping`` as it is doubling effort at the moment anyway. 

Could you share a small example data, that leads to the Error? So I can take a look. Just if it is not sensitive data.

**Comment by jeffzoch** [comment]
The test i run is incredibly simple - i just create 1 ticket with random data and insert it using the function ive shown you. Full schema shown below:
```kotlin
@Entity
@Table(name = "ticket")
data class Ticket(
        @Id
        @field:Column(name = "ticket_id") val ticketId: String = UUID.randomUUID().toString(),
        @field:Column(name = "job_id") val jobId: String = UUID.randomUUID().toString(),
        @field:Column(name = "entity_id") val entityId: String? = "",
        @field:Column(name = "step_no") val stepNo: Long = 0,
        @field:Column(name = "op_type") val opType: String,
        @Enumerated(EnumType.STRING)
        @field:Column(name = "status") val status: TicketStatus = TicketStatus.NEW,
        @field:Column(name = "created_by") val createdBy: String? = "",
        @field:Column(name = "reset_by") val resetBy: String? = "",
        @field:Column(name = "scheduled_start_time") val scheduledStartTime: Timestamp = Timestamp.from(Instant.now()),
        @field:Column(name = "scheduled_end_time") val scheduledEndTime: Timestamp? = null,
        @field:Column(name = "start_time") val startTime: Timestamp? = null,
        @field:Column(name = "end_time") val endTime: Timestamp? = null,
        @field:Column(name = "retryable") val retryable: Boolean = true,
        @field:Column(name = "retry_count") val retryCount: Int = 0,
        @field:Column(name = "cleanup_step") val cleanupStep: Int = 0,
        @field:Column(name = "assigned_to") val assignedTo: String? = "",
        @field:Column(name = "external_ref_id") val externalRefId: String? = "",
        @field:Column(name = "ticket_detail",length = 1000) val ticketDetail: String? = "",
        @CreationTimestamp
        @field:Column(name = "created_time") val createdTime: Timestamp = Timestamp.from(Instant.now()),
        @field:Column(name = "updated_by") val updatedBy: String? = "",
        @field:Column(name = "dry_run") val dryRun: Boolean = false,
        @field:Column(name = "cancel_requested") val cancelRequested: Boolean = false,
        @field:Column(name = "abort_code") val abortCode: String? = null,
        @field:Column(name = "error_code") val errorCode: String? = null
)
```

and here is the full function for trying to use the copy func:

```kotlin 
override fun postgresCopy(tickets: List<Ticket>): Result<Unit> {
        if (!dbName.contains("postgres")) return Result.failure(RuntimeException("Wrong db type"))
        return Try<Unit> {
            jdbc.dataSource?.connection?.use { conn ->
                PostgreSqlUtils.tryGetPGConnection(conn).map {
                    logger.info("Using postgres copy for insertion")
                    val typeMap = PostgresTypeMapping().mappings.apply {
                        put(Timestamp::class.java, DataType.Timestamp)
                    }
                    class TicketMapping(entityClass: Class<Ticket> = Ticket::class.java,
                                        typeMapping: IPostgresTypeMapping = PostgresTypeMapping(),
                                        columnMapping: MutableMap<String, DataType> = mutableMapOf() ,
                                        usePostgresQuoting: Boolean = false
                    ) : JpaMapping<Ticket>(entityClass, typeMapping, columnMapping, usePostgresQuoting) {
                        init {
                            this.getColumns().removeIf { c ->
                                    c.columnName == "scheduled_start_time"
                                    || c.columnName== "scheduled_end_time"
                                            || c.columnName== "start_time"
                                            || c.columnName== "end_time"
                                            || c.columnName == "created_time"
                            }

                            mapTimeStamp("scheduled_start_time") {t: Ticket -> t.scheduledStartTime.toLocalDateTime() }
                            mapTimeStamp("scheduled_end_time") {t: Ticket -> t.scheduledEndTime?.toLocalDateTime()  }
                            mapTimeStamp("start_time") {t: Ticket -> t.startTime?.toLocalDateTime() }
                            mapTimeStamp("end_time") {t: Ticket -> t.endTime?.toLocalDateTime() }
                            mapTimeStamp("created_time") {t: Ticket -> t.createdTime.toLocalDateTime() }

                        }
                    }
                    val mapping = TicketMapping(typeMapping = PostgresTypeMapping(typeMap))
                    val bulkInsert = PgBulkInsert(mapping)
                    logger.info("Copy: ${mapping.copyCommand}")
                    bulkInsert.saveAll(it, tickets)
                    conn.commit()
                }
            } ?: throw RuntimeException("No connection found")

        }
    }

```

**Comment by bytefish** [comment]
As for the Not Enough Data Left Error, it has mostly to do with a Postgres Type mismatch, let's say you are using an Integer in Java and want to map to something like an ``int2`` in Postgres. I assume your ``retryCount`` isn't a full-blown ``int4`` in Java.

That's why I added the ``@PostgresDataType(...)`` annotation, you you could map explicitly what data type the property maps to.

**Comment by jeffzoch** [comment]
Ah that makes sense. Sorry all my code is in kotlin btw, not sure how familiar you are with it :/

**Comment by bytefish** [comment]
Not really, but it looks like JetBrains put Java and C# in a mixer and Kotlin came out. So it's understandable. Sorry, I edited my comment above, could you share the DDL for the SQL table if this isn't a problem.

**Comment by jeffzoch** [comment]
ticket_id,text,
abort_code,text,
assigned_to,text,
cancel_requested,boolean,
cleanup_step,numeric,
created_by,text,
created_time,timestamp without time zone,
dry_run,boolean,
end_time,timestamp without time zone,
entity_id,text,
error_code,text,
external_ref_id,text,
job_id,text,
op_type,text,
reset_by,text,
retry_count,numeric,
retryable,boolean,
scheduled_end_time,timestamp without time zone,
scheduled_start_time,timestamp without time zone,
start_time,timestamp without time zone,
status,text,
step_no,numeric,
ticket_detail,text,
updated_by,text,



Here is a dump of the schema from pg

**Comment by bytefish** [comment]
Yes and there is one of the Problems already. I really regret adding a JpaMapping. The Probability is way too high, that the default assumptions (``int`` in java -> ``int4`` in Postgres) fail to hold. This means you would have to pollute your mappings with a million explicit ``PgDataType`` annotations... leaving users like you wondering why use it at all then?

Just the same with the DateTime. What should it be mapped to by default?

You are right, some of this can be alleviated by reading the actual database using Hibernate, but I don't think I can implement it. This makes me think: I'll drop the ``JpaMapping<>`` and make a simplified version as a recipe in the README.

**Comment by bytefish** [comment]
OK, I have added a Unit Test in a Branch, that implements the ``AbstractMapping``:

```java
private static class TicketMapping extends AbstractMapping<Ticket> {
public TicketMapping(String schema) {
    super(schema, "unit_test");

    mapText("job_id", x -> x.jobId);
    mapText("entity_id", x -> x.entityId);
    mapNumeric("step_no", x -> x.stepNo);
    mapText("status", x -> x.status != null ? x.status.name() : null);
    mapText("op_type", x -> x.opType);
    mapText("created_by", x -> x.createdBy);
    mapText("reset_by", x -> x.resetBy);
    mapTimeStamp("scheduled_end_time", x -> x.scheduledEndTime != null ? x.scheduledEndTime.toLocalDateTime() : null);
    mapTimeStamp("scheduled_start_time", x -> x.scheduledStartTime != null ? x.scheduledStartTime.toLocalDateTime() : null);
    mapTimeStamp("start_time", x -> x.startTime != null ? x.startTime.toLocalDateTime() : null);
    mapTimeStamp("end_time", x -> x.endTime != null ? x.endTime.toLocalDateTime() : null);
    mapBoolean("retryable", x -> x != null ? x.retryable : null);
    mapNumeric("retry_count", x -> x.retryCount);
    mapNumeric("cleanup_step", x -> x.cleanupStep);
    mapText("assigned_to", x -> x.assignedTo);
    mapText("external_ref_id", x -> x.externalRefId);
    mapText("ticket_detail", x -> x.ticketDetail);
    mapTimeStamp("created_time",  x -> x.createdTime != null ? x.createdTime.toLocalDateTime() : null);
    mapText("updated_by", x -> x.updatedBy);
    mapBoolean("dry_run", x -> x != null ? x.dryRun : null);
    mapBoolean("cancel_requested", x -> x != null ? x.cancelRequested : null);
    mapText("abort_code", x -> x.abortCode);
    mapText("error_code", x -> x.errorCode);
}
```

Now let me just write down what I think. 

Implementing a ``JpaMapping`` was the wrong route from the start, because a user should know exactely how to map the data, else the Binary Copy in Postgres will fail. And a ``JpaMapping`` gives the false assumption (just like you expected), that I just drop it in and it magically resolves the Schema details. At least, that's what I would expect from a library!

But no Matter how much energy I will put into the ``JpaMapping``, there will always be JPA / Hibernate corner cases I cannot cover (Composite Keys, Associtation Tables, Lazy Loading, weird Enumerations, ...) and I think JPA itself has a lot of stuff you can add... for example ``RevisionEntities`` when using Hibernate Envers. 

And I think a lot of people might have something like it lingering in their JPA data model, and rightly so because it is needed. But supporting it for a tiny library with a very specific problem... is way too much for me as a maintainer.

That's why I will raise the version to 7.0.0 and remove the JpaMapping from the project.

It gives false expectations.

**Comment by bytefish** [comment]
OK, I have removed the ``JpaMapping`` from future Releases. The 7.0.0 will be available sometime soon, but does not contain any changes except dropping the ``JpaMapping``. I wanted to do a hard cut, so people know from 7.0.0 there is no such thing as a ``JpaMapping``. 

I am sorry for this lengthy thread, please let me know if the ``AbstractMapping`` fixes your problem.

**Comment by jeffzoch** [comment]
That seems fair! I am debugging a EOF exception using pretty much the same schema you used but ill let you know how it works. Posting snippet for compelteness. Thanks for all the help! Ill be driving for the next 10 hours so ill try to debug this tomorrow.
```kotlin
override fun postgresCopy(tickets: List<Ticket>): Result<Unit> {
        if (!dbName.contains("postgres")) return Result.failure(RuntimeException("Wrong db type"))
        return Try<Unit> {
            val conn: Connection = jdbc.dataSource?.connection ?: throw RuntimeException("No connection found")
            val pgConn = PostgreSqlUtils.tryGetPGConnection(jdbc.dataSource?.connection)
                    .orElseThrow { RuntimeException("No PGConnection available") }
            logger.info("Using postgres copy for insertion of ${tickets.size} tickets.")
            class TicketMapping : AbstractMapping<Ticket> {
                constructor(schemaName: String = "public", tableName: String = "ticket") : super(schemaName, tableName) {
                    mapVarChar("ticket_id", Ticket::ticketId)
                    mapVarChar("job_id", Ticket::jobId)
                    mapVarChar("entity_id", Ticket::entityId)
                    mapNumeric("step_no", Ticket::stepNo)
                    mapVarChar("op_type", Ticket::opType)
                    mapVarChar("status") { t -> t.status.name }
                    mapVarChar("created_by", Ticket::createdBy)
                    mapVarChar("reset_by", Ticket::resetBy)
                    map("retryable", DataType.Boolean) { t -> t.retryable }
                    mapNumeric("retry_count", Ticket::retryCount)
                    mapNumeric("cleanup_step", Ticket::cleanupStep)
                    mapVarChar("assigned_to", Ticket::assignedTo)
                    mapVarChar("external_ref_id", Ticket::externalRefId)
                    mapVarChar("updated_by", Ticket::updatedBy)
                    map("dry_run", DataType.Boolean) { t -> t.dryRun }
                    map("cancel_requested", DataType.Boolean) { t -> t.cancelRequested }
                    mapVarChar("abort_code", Ticket::abortCode)
                    mapVarChar("error_code", Ticket::errorCode)
                    mapTimeStamp("scheduled_start_time") { t: Ticket -> t.scheduledStartTime.toLocalDateTime() }
                    mapTimeStamp("scheduled_end_time") { t: Ticket -> t.scheduledEndTime?.toLocalDateTime() }
                    mapTimeStamp("start_time") { t: Ticket -> t.startTime?.toLocalDateTime() }
                    mapTimeStamp("end_time") { t: Ticket -> t.endTime?.toLocalDateTime() }
                    mapTimeStamp("created_time") { t: Ticket -> t.createdTime.toLocalDateTime() }
                }
            }
            val mapping = TicketMapping(schemaName = conn.schema ?: "public")
            mapping.columns.forEach { c ->
                logger.info("Column defined in PGCopy: ${c.columnName}")
            }
            val bulkInsert = PgBulkInsert(mapping)
            logger.info("Postgres Copy Command: ${mapping.copyCommand}")
            bulkInsert.saveAll(pgConn, tickets)
            conn.close()
        }
    }
```

**Comment by bytefish** [comment]
Maybe it's just me not understanding Kotlin, but why don't you pass in a lambda function as the second parameter: 

```
mapTimeStamp("scheduled_end_time") { t: Ticket -> t.scheduledEndTime?.toLocalDateTime() }
```

Or does Kotlin do it automatically?

I would have expected:

```
mapTimeStamp("scheduled_end_time", t: Ticket -> t.scheduledEndTime?.toLocalDateTime())
```
